source "https://rubygems.org"

group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-spaceship", "~> 0.5.3"
end

group :test do
  gem "html-proofer"
  gem "mdl"
  gem "rake"
end

gem "webrick", "~> 1.8"
